name: CI

on:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install pluck
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: maxdeviant/pluck
          platform: linux
          arch: x86_64

      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Last.fm
        run: pluck lastfm data/last.fm
        continue-on-error: true
        env:
          LASTFM_USER: maxdeviant
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}

      - name: Sync Bluesky
        run: pluck bluesky data/bluesky
        continue-on-error: true
        env:
          BLUESKY_HANDLE: maxdeviant.com
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}

      - name: Commit and push (if changed)
        if: github.ref == 'refs/heads/master'
        run: |-
          git diff
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/last.fm/*.toml
          git add data/bluesky/*.toml
          git commit --message "Update data" || exit 0
          git push
