name: CI

on:
  push: [master]
  schedule:
    - cron "0 */1 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install pluck
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with:
          repo: maxdeviant/pluck
          platform: linux
          arch: x86-64

      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Last.fm
        run: pluck lastfm data/last.fm
        env:
          LASTFM_USER: maxdeviant
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}

      - name: Commit and push (if changed)
        if: github.ref == 'refs/heads/master'
        run: |-
          git diff
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -u
          git commit -m "Update data" || exit 0
          git push
